### PR TITLE
Documentation review and formatting

### PR DESCRIPTION
**Pull request by damb**
This PR includes a documentation review of both module configuration parameters and the application's `README` file. It mainly fixes typos and grammar issues. Similar issues are fixed in source code comments, too.

Besides, some formatting issues are corrected.

Solves #40.

### CODE REVIEW

**Comment by luca-s** [comment]
thanks a lot (y) I will review this soon

**Comment by damb** [comment]
> Thanks a lot, I will review this soon

@luca-s, it is still marked as WIP. I let you know if it is ready for review.

**Comment by damb** [comment]
@luca-s, ready to be reviewed.

Note, that I didn't fix the indentation of `apps/scrtdd/descriptions/scrtdd.xml`. IMO, it would be good to do so.

**Comment by damb** [comment]
Ok. I resolved the merge conflict.

**Comment by luca-s** [comment]
Wow, thanks a lot. I will review this soon.

> Note, that I didn't fix the indentation of apps/scrtdd/descriptions/scrtdd.xml. IMO, it would be good to do so.

This is a good idea.

**Comment by luca-s** [comment]
Merged! Thanks a lot

**Comment by damb** [comment]
Thanks for merging. 

Though, the outputs of `scrtdd --help` within the `README` might have been diverged. Did you verify that?

**Comment by luca-s** [comment]
Good point! I will have to update that too

**Pull request merged**
